// User Types
export interface UserSettings {
  syncMode: 'wifi_only' | 'wifi_and_mobile' | 'manual';
  uploadQuality: 'original' | 'high' | 'medium';
  autoBackup: boolean;
  faceRecognition: boolean;
  darkMode: boolean;
}

export interface User {
  id: string;
  email: string;
  displayName: string;
  avatarUrl?: string;
  createdAt: Date;
  settings: UserSettings;
  storageUsed: number;
  storageLimit: number;
  subscriptionIds: string[];
  familyId?: string;
  role: 'user' | 'family_admin' | 'business_admin';
}

// File Types
export type FileType = 'image' | 'video' | 'document' | 'other';

export interface FaceData {
  personId?: string;
  boundingBox: {
    x: number;
    y: number;
    width: number;
    height: number;
  };
  confidence: number;
}

export interface GeoLocation {
  latitude: number;
  longitude: number;
}

export interface FileMetadata {
  id: string;
  userId: string;
  familyId?: string;
  type: FileType;
  name: string;
  size: number;
  mimeType: string;
  s3Key: string;
  thumbnailKey?: string;
  smallThumbKey?: string;
  largeThumbKey?: string;

  // Image/Video metadata
  width?: number;
  height?: number;
  duration?: number;
  takenAt?: Date;
  location?: GeoLocation;
  deviceInfo?: string;

  // AI Data
  labels?: string[];
  faces?: FaceData[];
  ocrText?: string;
  isNsfw?: boolean;
  qualityScore?: number;

  // Organization
  albumIds: string[];
  isFavorite: boolean;
  isArchived: boolean;
  isTrashed: boolean;
  trashedAt?: Date;

  createdAt: Date;
  updatedAt: Date;
}

// Album Types
export interface Album {
  id: string;
  userId: string;
  name: string;
  description?: string;
  coverFileId?: string;
  isAutoGenerated: boolean;
  isShared: boolean;
  sharedWith: string[];
  shareLink?: string;
  fileCount: number;
  createdAt: Date;
  updatedAt: Date;
}

// Shared Link Types
export interface SharedLink {
  token: string;
  type: 'file' | 'album';
  fileId: string;
  userId: string;
  // Denormalized from FileMetadata for public display (avoids reading private files collection)
  fileName: string;
  fileType: FileType;
  mimeType: string;
  width?: number;
  height?: number;
  // Metadata
  createdAt: Date;
  expiresAt?: Date;
  viewCount: number;
  isActive: boolean;
}

// Family Types
export interface Family {
  id: string;
  name: string;
  adminId: string;
  memberIds: string[];
  sharedStorageUsed: number;
  createdAt: Date;
}

// Subscription Types
export type SubscriptionStatus = 'active' | 'paused' | 'cancelled' | 'past_due';

export interface Subscription {
  id: string;
  userId: string;
  tier: number;
  storageAmount: number;
  status: SubscriptionStatus;
  billingPeriod?: BillingPeriod;
  currentPeriodEnd: Date;
  paddleCustomerId: string;
  createdAt: Date;
}

// Person (Face Recognition) Types
export interface Person {
  id: string;
  userId: string;
  name?: string;
  faceEmbedding: number[];
  sampleFileIds: string[];
  photoCount: number;
  createdAt: Date;
}

// API Request/Response Types
export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  pageSize: number;
  hasMore: boolean;
}

export interface UploadUrlResponse {
  uploadUrl: string;
  fileId: string;
  expiresAt: Date;
}

export interface FileUploadConfirmation {
  fileId: string;
  s3Key: string;
  size: number;
  mimeType: string;
}

export interface SearchFilters {
  type?: FileType;
  dateFrom?: Date;
  dateTo?: Date;
  albumId?: string;
  isFavorite?: boolean;
  isArchived?: boolean;
}

export interface SearchRequest {
  query: string;
  filters?: SearchFilters;
  page?: number;
  pageSize?: number;
}

// AI Processing Types
export interface AIProcessingResult {
  labels: string[];
  faces: FaceData[];
  ocrText?: string;
  isNsfw: boolean;
  qualityScore: number;
}

// Billing Period Types
export type BillingPeriod = 'monthly' | 'quarterly' | 'semiAnnual' | 'yearly';

// Storage Tier Types
export interface StorageTier {
  tier: number;
  name: string;
  storageBytes: number;
  storageDisplay: string;
  // Standard pricing (without AI)
  priceMonthly: number;
  priceQuarterly: number;
  priceSemiAnnual: number;
  priceYearly: number;
  paddleProductId: string;
  paddleQuarterlyId: string;
  paddleSemiAnnualId: string;
  paddleYearlyId: string;
  // AI pricing
  priceMonthlyAI: number;
  priceQuarterlyAI: number;
  priceSemiAnnualAI: number;
  priceYearlyAI: number;
  paddleProductIdAI: string;
  paddleQuarterlyIdAI: string;
  paddleSemiAnnualIdAI: string;
  paddleYearlyIdAI: string;
  // Features
  features: string[];
  aiFeatures?: string[];
  isPopular?: boolean;
}

// Memory/Suggestion Types
export interface Memory {
  id: string;
  title: string;
  description: string;
  files: FileMetadata[];
  date: Date;
  type: 'on_this_day' | 'best_of_month' | 'trip' | 'collection';
}
