// User Types
export interface UserSettings {
  syncMode: 'wifi_only' | 'wifi_and_mobile' | 'manual';
  uploadQuality: 'original' | 'high' | 'medium';
  autoBackup: boolean;
  allowRoaming: boolean;
  faceRecognition: boolean;
  darkMode: boolean;
  backupFolders: string[]; // Device album/folder titles to backup (empty = all folders)
  // Storage allocation — how much of total storage is dedicated to MySpace vs MyPhoto
  myDiskAllocatedBytes?: number; // If set, rest goes to MyPhoto. If not set, auto-managed.
}

export interface User {
  id: string;
  email: string;
  displayName: string;
  avatarUrl?: string;
  createdAt: Date;
  settings: UserSettings;
  storageUsed: number;
  storageLimit: number;
  subscriptionIds: string[];
  familyId?: string;
  role: 'user' | 'family_admin' | 'business_admin';
  referralCode: string;
  referredBy?: string;
  referralCount: number;
  referralBonusBytes: number;
  backupBonusClaimed?: boolean;
  desktopBonusClaimed?: boolean;
  // Track referral qualification (must upload 100MB to qualify referrer for bonus)
  totalUploadedBytes?: number;
  referralQualified?: boolean;
}

export interface Referral {
  id: string;
  referrerUserId: string;
  refereeUserId: string;
  refereeEmail: string;
  bonusBytes: number;
  qualified: boolean; // true only after referee uploads 100MB
  createdAt: Date;
}

// File Types
export type FileType = 'image' | 'video' | 'document' | 'other';

export interface FaceAttributes {
  age?: number;
  gender?: 'male' | 'female';
  hairColor?: 'black' | 'brown' | 'blonde' | 'red' | 'gray' | 'white';
  expression?: string;
  glasses?: boolean;
  beard?: boolean;
}

export interface FaceData {
  personId?: string;
  boundingBox: {
    x: number;
    y: number;
    width: number;
    height: number;
  };
  confidence: number;
  attributes?: FaceAttributes;
}

// Rich scene attributes extracted by AI
export type TimeOfDay = 'dawn' | 'morning' | 'afternoon' | 'evening' | 'night';
export type ArchitectureStyle = 'modern' | 'old' | 'industrial' | 'rural' | 'none';
export type WeatherCondition = 'sunny' | 'cloudy' | 'rainy' | 'snowy' | 'foggy' | 'unknown';

export interface SceneAttributes {
  // Landscape & environment
  landscape?: string[];    // 'hills', 'meadow', 'forest', 'river', 'lake', 'sea', 'desert', 'field'
  urban?: string[];        // 'city', 'street', 'building', 'skyscraper', 'bridge', 'park'
  architecture?: ArchitectureStyle;
  indoor?: boolean;

  // Time & weather
  timeOfDay?: TimeOfDay;
  weather?: WeatherCondition;
  season?: 'spring' | 'summer' | 'autumn' | 'winter';

  // Activity & context
  activity?: string[];     // 'sport', 'celebration', 'travel', 'work', 'food', 'selfie'
  mood?: string;           // 'happy', 'calm', 'energetic', 'romantic'
}

export interface GeoLocation {
  latitude: number;
  longitude: number;
}

export interface FileMetadata {
  id: string;
  userId: string;
  familyId?: string;
  type: FileType;
  name: string;
  size: number;
  mimeType: string;
  s3Key: string;
  thumbnailKey?: string;
  smallThumbKey?: string;
  largeThumbKey?: string;

  // Image/Video metadata
  width?: number;
  height?: number;
  duration?: number;
  takenAt?: Date;
  location?: GeoLocation;
  locationName?: string; // Reverse-geocoded place name (e.g. "Vranje, Serbia")
  deviceInfo?: string;

  // AI Data
  labels?: string[];
  faces?: FaceData[];
  ocrText?: string;
  isNsfw?: boolean;
  qualityScore?: number;
  sceneType?: string;
  sceneAttributes?: SceneAttributes;
  dominantColors?: string[];
  pHash?: string;

  // Cross-reference to MySpace (disk) — links photo to its source file/folder
  diskFileId?: string;   // ID in diskFiles collection (same physical file)
  diskFolderId?: string; // Folder in MySpace where the original file lives

  // Organization
  albumIds: string[];
  isFavorite: boolean;
  isArchived: boolean;
  isTrashed: boolean;
  trashedAt?: Date;

  createdAt: Date;
  updatedAt: Date;
}

// MySpace (Disk) Types
export interface DiskFolder {
  id: string;
  userId: string;
  name: string;
  parentId: string;
  path: string;
  isTrashed?: boolean;
  trashedAt?: Date;
  createdAt: Date;
  updatedAt: Date;
}

export interface DiskFile {
  id: string;
  userId: string;
  name: string;
  s3Key: string;
  mimeType: string;
  size: number;
  folderId: string;
  isTrashed?: boolean;
  trashedAt?: Date;
  // Cross-reference to MyPhoto — if this is an image/video, links to the photo record
  photoFileId?: string;
  createdAt: Date;
  updatedAt: Date;
}

// Album Types
export interface Album {
  id: string;
  userId: string;
  name: string;
  description?: string;
  coverFileId?: string;
  isAutoGenerated: boolean;
  isShared: boolean;
  sharedWith: string[];
  shareLink?: string;
  fileCount: number;
  createdAt: Date;
  updatedAt: Date;
}

// Shared Link Types
export type SharePermission = 'read' | 'readwrite';

export interface SharedLink {
  token: string;
  type: 'file' | 'album';
  fileId: string;
  userId: string;
  // Denormalized from FileMetadata for public display (avoids reading private files collection)
  fileName: string;
  fileType: FileType;
  mimeType: string;
  width?: number;
  height?: number;
  // Permission level for shared content
  permission: SharePermission;
  // Album metadata
  albumId?: string;
  albumName?: string;
  albumDescription?: string;
  albumFileIds?: string[];
  albumFileCount?: number;
  coverFileId?: string;
  // Metadata
  createdAt: Date;
  expiresAt?: Date;
  viewCount: number;
  isActive: boolean;
}

// Family Types
export interface Family {
  id: string;
  name: string;
  adminId: string;
  memberIds: string[];
  sharedStorageUsed: number;
  createdAt: Date;
}

// Subscription Types
export type SubscriptionStatus = 'active' | 'paused' | 'cancelled' | 'past_due';

export interface Subscription {
  id: string;
  userId: string;
  tier: number;
  storageAmount: number;
  status: SubscriptionStatus;
  billingPeriod?: BillingPeriod;
  currentPeriodEnd: Date;
  paddleCustomerId: string;
  createdAt: Date;
}

// Person (Face Recognition) Types
export interface Person {
  id: string;
  userId: string;
  name?: string;
  faceEmbedding: number[];
  sampleFileIds: string[];
  photoCount: number;
  createdAt: Date;
}

// API Request/Response Types
export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  pageSize: number;
  hasMore: boolean;
}

export interface UploadUrlResponse {
  uploadUrl: string;
  fileId: string;
  expiresAt: Date;
}

export interface FileUploadConfirmation {
  fileId: string;
  s3Key: string;
  size: number;
  mimeType: string;
}

export interface SearchFilters {
  type?: FileType;
  dateFrom?: Date;
  dateTo?: Date;
  albumId?: string;
  isFavorite?: boolean;
  isArchived?: boolean;
}

export interface SearchRequest {
  query: string;
  filters?: SearchFilters;
  page?: number;
  pageSize?: number;
}

// AI Processing Types
export interface AIProcessingResult {
  labels: string[];
  faces: FaceData[];
  ocrText?: string;
  isNsfw: boolean;
  qualityScore: number;
}

// Billing Period Types — only monthly and yearly
export type BillingPeriod = 'monthly' | 'yearly';

// Storage Tier Types
export interface StorageTier {
  tier: number;
  name: string;
  storageBytes: number;
  storageDisplay: string;
  priceMonthly: number;
  priceYearly: number;
  paddleMonthlyId: string;
  paddleYearlyId: string;
  features: string[];
  isPopular?: boolean;
}

// Memory/Suggestion Types
export interface Memory {
  id: string;
  title: string;
  description: string;
  files: FileMetadata[];
  date: Date;
  type: 'on_this_day' | 'best_of_month' | 'trip' | 'collection';
}
