import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/lib/firebase-admin';
import { verifyAuthWithRateLimit } from '@/lib/auth-utils';
import { generateDownloadUrl } from '@/lib/s3';

export const dynamic = 'force-dynamic';

// GET /api/albums — list the caller's albums newest-first. fileCount is
// stored denormalised on the album doc; we don't try to recompute it on
// every read because it would dominate the query cost for big libraries.
export async function GET(request: NextRequest) {
  const auth = await verifyAuthWithRateLimit(request, 'api');
  if (!auth.success) return auth.response;

  const snap = await db
    .collection('albums')
    .where('userId', '==', auth.userId)
    .orderBy('createdAt', 'desc')
    .get();

  const albums = await Promise.all(
    snap.docs.map(async (doc) => {
      const data = doc.data();
      const album: Record<string, unknown> = {
        id: doc.id,
        ...data,
        createdAt: data.createdAt?.toDate?.()?.toISOString() || data.createdAt || null,
        updatedAt: data.updatedAt?.toDate?.()?.toISOString() || data.updatedAt || null,
      };
      // Surface a thumbnail for the cover so mobile doesn't need a
      // separate round-trip to /api/files/{coverFileId}.
      if (data.coverFileId) {
        try {
          const coverDoc = await db.collection('files').doc(data.coverFileId).get();
          const coverKey = coverDoc.data()?.smallThumbKey || coverDoc.data()?.thumbnailKey;
          if (coverKey) album.coverThumbUrl = await generateDownloadUrl(coverKey);
        } catch {
          // Cover lookup is best-effort; missing cover is fine.
        }
      }
      return album;
    })
  );

  return NextResponse.json({ albums });
}

// POST /api/albums — create a new (manual) album. Auto-generated albums
// (people, places, …) come from background jobs and bypass this route.
export async function POST(request: NextRequest) {
  const auth = await verifyAuthWithRateLimit(request, 'api');
  if (!auth.success) return auth.response;

  const body = await request.json().catch(() => ({}));
  const name = typeof body?.name === 'string' ? body.name.trim() : '';
  const description = typeof body?.description === 'string' ? body.description.trim() : '';

  if (!name) {
    return NextResponse.json({ error: 'name required' }, { status: 400 });
  }
  if (name.length > 80) {
    return NextResponse.json({ error: 'name too long (max 80)' }, { status: 400 });
  }

  const now = new Date();
  const ref = await db.collection('albums').add({
    userId: auth.userId,
    name,
    description: description || null,
    coverFileId: null,
    isAutoGenerated: false,
    isShared: false,
    sharedWith: [],
    fileCount: 0,
    createdAt: now,
    updatedAt: now,
  });

  return NextResponse.json({
    id: ref.id,
    name,
    description: description || null,
    fileCount: 0,
    isAutoGenerated: false,
    isShared: false,
    createdAt: now.toISOString(),
  });
}
